Vagrant.configure("2") do |config|
  config.vm.box = "bytesguy/ubuntu-server-20.04-arm64"
  config.vm.box_check_update = false
  config.vm.box_version = "1.0.0"
  
  config.vm.provider "vmware_desktop" do |v|
    v.memory = "1024"
    v.cpus = 1
    v.vmx["ethernet0.pcislotnumber"] = "160"
  end
end

